In [1]:
import os
import numpy as np
import pandas as pd

os.path.join(path, *paths)
Join one or more path components intelligently. The return value is the concatenation of path and any members of *paths with exactly one directory separator (os.sep) following each non-empty part except the last, meaning that the result will only end in a separator if the last part is empty. If a component is an absolute path, all previous components are thrown away and joining continues from the absolute path component.
X = [] # an element of X is represented as (filename,text)
Y = [] # an element of Y represents the newsgroup category of the corresponding X element

In [2]:
data = {}
X = []
Y = []
for folder in os.listdir('20_newsgroups'):
    for file in os.listdir(os.path.join('20_newsgroups',folder)):
        with open(os.path.join('20_newsgroups',folder,file) , "r") as f:
            X.append((file , f.read()))
            Y.append(folder)

In [4]:
#Creating set of stopwords

from nltk.corpus import stopwords
from string import punctuation

sw = list(stopwords.words('english'))
sw += list(punctuation)
sw += ['subject:','from:', 'date:', 'newsgroups:', 'message-id:', 'lines:', 'path:', 'organization:', 
            'would', 'writes:', 'references:', 'article', 'sender:', 'nntp-posting-host:', 'people', 
            'university', 'think', 'xref:', 'cantaloupe.srv.cs.cmu.edu', 'could', 'distribution:', 'first', 
            'anyone','world', 'really', 'since', 'right', 'believe', 'still', 'keywords','expires','approved'
            ,'archive','name','to:','or:','telephone:','fax:','reply-to:',"that's",'followup-to:',"we're",
            "let's", "what's","max>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'","going","using",]

In [5]:
print(X[1][1])

Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51060 alt.atheism.moderated:727 news.answers:7300 alt.answers:155
Path: cantaloupe.srv.cs.cmu.edu!crabapple.srv.cs.cmu.edu!fs7.ece.cmu.edu!europa.eng.gtefsd.com!howland.reston.ans.net!agate!netsys!ibmpcug!mantis!mathew
From: mathew <mathew@mantis.co.uk>
Newsgroups: alt.atheism,alt.atheism.moderated,news.answers,alt.answers
Subject: Alt.Atheism FAQ: Introduction to Atheism
Summary: Please read this file before posting to alt.atheism
Keywords: FAQ, atheism
Message-ID: <19930405122245@mantis.co.uk>
Date: Mon, 5 Apr 1993 12:22:45 GMT
Expires: Thu, 6 May 1993 12:22:45 GMT
Followup-To: alt.atheism
Distribution: world
Organization: Mantis Consultants, Cambridge. UK.
Approved: news-answers-request@mit.edu
Supersedes: <19930308134439@mantis.co.uk>
Lines: 646

Archive-name: atheism/introduction
Alt-atheism-archive-name: introduction
Last-modified: 5 April 1993
Version: 1.2

-----BEGIN PGP SIGNED MESSAGE-----

                          An Introduction t

In [6]:
#Removing stop words from words list

def filter_words(words):
    useful_words = [w for w in words if w not in sw]
    return useful_words

In [8]:
#converting sentences into tokens
from nltk.tokenize import word_tokenize

vocab = {} 
for i in range(len(X)):
    words = word_tokenize(X[i][1].lower())
    useful_words = filter_words(words)
    for j in useful_words:
        if j in vocab:
            vocab[j]+=1
        else:
            vocab[j] = 1

In [9]:
vocab['atheism']

400

In [10]:
from operator import itemgetter
vocab = dict(sorted(vocab.items() , key = itemgetter(1) , reverse = True))

In [11]:
print(max(vocab.values())+1)

186473


In [12]:
import matplotlib.pyplot as plt

#y-axis
size = max(vocab.values())+1
No_of_words = [0] * size
#x-axis
Word_frequency = [i for i in range(size)]
#create list of count of no of words with specific frequency
for i in vocab:
    No_of_words[vocab[i]] +=1

#plotting the graph    
plt.plot(Word_frequency,No_of_words)
plt.axis([1, 25, 0, 20000])
plt.xlabel("Frequency")
plt.ylabel("No of words")
plt.grid()
plt.show()

<Figure size 640x480 with 1 Axes>

In [13]:
len(No_of_words)


186473

In [14]:
#Feature Words
feature = []
cutoff_freq = 80
for key in vocab:
    if vocab[key] >=cutoff_freq:
        feature.append(key)
len(feature)

6324

In [15]:
len(feature)

6324

In [16]:
print(str(X[0]))

('49960', 'Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49960 alt.atheism.moderated:713 news.answers:7054 alt.answers:126\nPath: cantaloupe.srv.cs.cmu.edu!crabapple.srv.cs.cmu.edu!bb3.andrew.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!magnus.acs.ohio-state.edu!usenet.ins.cwru.edu!agate!spool.mu.edu!uunet!pipex!ibmpcug!mantis!mathew\nFrom: mathew <mathew@mantis.co.uk>\nNewsgroups: alt.atheism,alt.atheism.moderated,news.answers,alt.answers\nSubject: Alt.Atheism FAQ: Atheist Resources\nSummary: Books, addresses, music -- anything related to atheism\nKeywords: FAQ, atheism, books, music, fiction, addresses, contacts\nMessage-ID: <19930329115719@mantis.co.uk>\nDate: Mon, 29 Mar 1993 11:57:19 GMT\nExpires: Thu, 29 Apr 1993 11:57:19 GMT\nFollowup-To: alt.atheism\nDistribution: world\nOrganization: Mantis Consultants, Cambridge. UK.\nApproved: news-answers-request@mit.edu\nSupersedes: <19930301143317@mantis.co.uk>\nLines: 290\n\nArchive-name: atheism/resources\nAlt-atheism-archive-name: resourc

X_train Dataset and Y_Train Dataset for naive bayes implementation
We will be building a counting vector

In [17]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.25, random_state=0)

1.) Created an array of zeros of shape no_of_feature * total_X_Train elements
2.) And then for each element each word of it is checked whether it matches any feature
3.) if yes then that particural cell for that word of that element is incremented

In [18]:
X_train_dataset = np.zeros((len(X_train),len(feature)))

for i in range(len(X_train)):
    word_list = word_tokenize(X_train[i][1].lower())
    for word in word_list:
        if(word in feature):
            X_train_dataset[i][feature.index(word)] += 1

In [19]:
print(X_train_dataset)

[[1. 0. 3. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [1. 0. 2. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]]


In [20]:
X_test_dataset = np.zeros((len(X_test),len(feature)))

for i in range(len(X_test)):
    word_list = word_tokenize(X_test[i][1].lower())
    for word in word_list:
        if(word in feature):
            X_test_dataset[i][feature.index(word)] += 1

In [21]:
len(Y_train)

14997

In [22]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [23]:
clf = MultinomialNB()
clf.fit(X_train_dataset,Y_train)
Y_test_pred = clf.predict(X_test_dataset)
sklearn_score_train = clf.score(X_train_dataset,Y_train)
print("Sklearn's score on training data :",sklearn_score_train)
sklearn_score_test = clf.score(X_test_dataset,Y_test)
print("Sklearn's score on testing data :",sklearn_score_test)
print("Classification report for testing data :-")
print(classification_report(Y_test, Y_test_pred))

Sklearn's score on training data : 0.873041274921651
Sklearn's score on testing data : 0.8304
Classification report for testing data :-
                          precision    recall  f1-score   support

             alt.atheism       0.77      0.84      0.81       233
           comp.graphics       0.67      0.83      0.74       253
 comp.os.ms-windows.misc       0.50      0.02      0.03       249
comp.sys.ibm.pc.hardware       0.56      0.89      0.68       240
   comp.sys.mac.hardware       0.79      0.92      0.85       236
          comp.windows.x       0.76      0.78      0.77       240
            misc.forsale       0.82      0.87      0.84       261
               rec.autos       0.89      0.90      0.89       269
         rec.motorcycles       0.92      0.96      0.94       284
      rec.sport.baseball       0.97      0.92      0.94       248
        rec.sport.hockey       0.97      0.97      0.97       231
               sci.crypt       0.94      0.93      0.94       233
     